---
- name: Invoke facter explicitly
  setup:

- name: Download and install FileBeat Debian
  shell: cd $(mktemp -d) && curl -L -O https://download.elastic.co/beats/filebeat/filebeat_1.3.0_amd64.deb && (dpkg -i filebeat_1.3.0_amd64.deb || true)
  when: ansible_os_family == "Debian"

- name: Download and install FileBeat RedHat
  shell: cd $(mktemp -d) && curl -L -O https://download.elastic.co/beats/filebeat/filebeat-1.3.0-x86_64.rpm && (rpm -vi filebeat-1.3.0-x86_64.rpm || true)
  when: ansible_os_family == "RedHat"

- name: Copy filebeat configuration
  template: src=filebeat.yml dest=/etc/filebeat/filebeat.yml

- name: Ensure FileBeat is restarted and enabled
  service: name=filebeat state=restarted enabled=yes
